# Generated by Django 4.2.5 on 2023-09-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='executed_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Executedsuccess'), (2, 'Executedfailed'), (3, 'Executiontimeout')], default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
    ]
