# Generated by Django 4.2.5 on 2023-09-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_manager', '0002_request_executed_status_alter_request_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='executed_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Failed'), (3, 'Timeout')], default=0),
        ),
    ]
