# Generated by Django 4.2.5 on 2023-09-22 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_manager', '0005_request_expiration_time_alter_provider_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='execution_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 22, 8, 3, 5, 368010), null=True),
        ),
    ]
