# Generated by Django 4.2.5 on 2023-09-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_manager', '0007_alter_request_execution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='executed_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Success'), (3, 'Failed'), (4, 'Timeout')], default=0),
        ),
    ]
